### ISSUE TITLE
DAVIS images?

### ISSUE THREAD

**Issue by supitalp** [PIX2NVS/NVS2Graph#1]
Hello,
Thanks for this dataset!
The paper mentions that the sequences were recorded with a DAVIS240C sensor. Are the corresponding grayscale images available? I could not find them on the website.

Thanks,
Henri

**Comment by PIX2NVS** [comment]
Hi, Thanks for your interests.
The dataset was recorded with DAVIS240c camera, but we did not enable the Image Sensor and IMU as well. Only the DVS events are available. Sorry about that.

**Comment by supitalp** [comment]
OK, thanks for your answer!
