### ISSUE TITLE
How to generate a graph?

### ISSUE THREAD

**Issue by jackfong123** [PIX2NVS/NVS2Graph#10]
Hello~ Thanks  for your great work! I want to configure my own dataset and use your code for the prediction! Could you please show how to generate a graph with the raw events? Thanks so much.

**Comment by PIX2NVS** [comment]
Hi thanks for the interests. Please kindly refer to Section 3.1 in the paper for the details.

**Comment by zhangxiann** [comment]
> Hi thanks for the interests. Please kindly refer to Section 3.1 in the paper for the details.

Where is the code for generating a graph with the raw events ???
