### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'view' when trying to run Test.py

### ISSUE THREAD

**Issue by vi-codes** [PIX2NVS/NVS2Graph#12]
Hi,
Thanks for making your code base available. I am quite new to pytorch and I am getting the following error on trying to run Test.py
 
/home/vi/Documents/NVS2Graph-master/code/Test.py:83: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with autograd.detect_anomaly():
tensor([2, 2, 5], device='cuda:0')
/home/vi/anaconda3/envs/env_for_torch/lib/python3.8/site-packages/torch_sparse/storage.py:382: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729096996/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  ptr = mask.nonzero().flatten()
Traceback (most recent call last):
  File "/home/vi/Documents/NVS2Graph-master/code/Test.py", line 154, in <module>
    train(epoch, train_batch_logger, train_loader)
  File "/home/vi/Documents/NVS2Graph-master/code/Test.py", line 87, in train
    end_point = model(data)
  File "/home/vi/anaconda3/envs/env_for_torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vi/Documents/NVS2Graph-master/code/Test.py", line 63, in forward
    x = x.view(-1, self.fc1.weight.size(1))
AttributeError: 'tuple' object has no attribute 'view'

@pix2nvs could you please help me in resolving this issue?

Thanks in advance!

**Comment by Shahmad99** [comment]
> Hi,
> Thanks for making your code base available. I am quite new to pytorch and I am getting the following error on trying to run Test.py
> 
> /home/vi/Documents/NVS2Graph-master/code/Test.py:83: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
> with autograd.detect_anomaly():
> tensor([2, 2, 5], device='cuda:0')
> /home/vi/anaconda3/envs/env_for_torch/lib/python3.8/site-packages/torch_sparse/storage.py:382: UserWarning: This overload of nonzero is deprecated:
> nonzero()
> Consider using one of the following signatures instead:
> nonzero(*, bool as_tuple) (Triggered internally at /opt/conda/conda-bld/pytorch_1603729096996/work/torch/csrc/utils/python_arg_parser.cpp:882.)
> ptr = mask.nonzero().flatten()
> Traceback (most recent call last):
> File "/home/vi/Documents/NVS2Graph-master/code/Test.py", line 154, in
> train(epoch, train_batch_logger, train_loader)
> File "/home/vi/Documents/NVS2Graph-master/code/Test.py", line 87, in train
> end_point = model(data)
> File "/home/vi/anaconda3/envs/env_for_torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/vi/Documents/NVS2Graph-master/code/Test.py", line 63, in forward
> x = x.view(-1, self.fc1.weight.size(1))
> AttributeError: 'tuple' object has no attribute 'view'
> 
> @PIX2NVS could you please help me in resolving this issue?
> 
> Thanks in advance!

I am facing same error, can you tell me how you solved this problem?

**Comment by doublemanyu** [comment]
@vi-codes Hi, did you solve the problem of "AttributeError: 'tuple' object has no attribute 'view'"? I am facing  the same error. I will appreciate it very much if you can share your solutions to the problem.

**Comment by sunlinhui** [comment]
> @vi-codes Hi, did you solve the problem of "AttributeError: 'tuple' object has no attribute 'view'"? I am facing the same error. I will appreciate it very much if you can share your solutions to the problem.

I have solved this problem.
The return of function max_pool_x is x and batch which forms the tuple. 
The details of max_pool_x can be found in : https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/pool/max_pool.html#max_pool_x

You can change the x = max_pool_x(cluster, data.x, data.batch, size=64) to x,_ = max_pool_x(cluster, data.x, data.batch, size=64).

I hope this solution can help you.

**Comment by sunlinhui** [comment]
> > Hi,
> > Thanks for making your code base available. I am quite new to pytorch and I am getting the following error on trying to run Test.py
> > /home/vi/Documents/NVS2Graph-master/code/Test.py:83: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
> > with autograd.detect_anomaly():
> > tensor([2, 2, 5], device='cuda:0')
> > /home/vi/anaconda3/envs/env_for_torch/lib/python3.8/site-packages/torch_sparse/storage.py:382: UserWarning: This overload of nonzero is deprecated:
> > nonzero()
> > Consider using one of the following signatures instead:
> > nonzero(*, bool as_tuple) (Triggered internally at /opt/conda/conda-bld/pytorch_1603729096996/work/torch/csrc/utils/python_arg_parser.cpp:882.)
> > ptr = mask.nonzero().flatten()
> > Traceback (most recent call last):
> > File "/home/vi/Documents/NVS2Graph-master/code/Test.py", line 154, in
> > train(epoch, train_batch_logger, train_loader)
> > File "/home/vi/Documents/NVS2Graph-master/code/Test.py", line 87, in train
> > end_point = model(data)
> > File "/home/vi/anaconda3/envs/env_for_torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> > result = self.forward(*input, **kwargs)
> > File "/home/vi/Documents/NVS2Graph-master/code/Test.py", line 63, in forward
> > x = x.view(-1, self.fc1.weight.size(1))
> > AttributeError: 'tuple' object has no attribute 'view'
> > @PIX2NVS could you please help me in resolving this issue?
> > Thanks in advance!
> 
> I am facing same error, can you tell me how you solved this problem?

I have solved this problem.
The return of function max_pool_x is x and batch which forms the tuple.
The details of max_pool_x can be found in : https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/pool/max_pool.html#max_pool_x

You can change the x = max_pool_x(cluster, data.x, data.batch, size=64) to x,_ = max_pool_x(cluster, data.x, data.batch, size=64).

I hope this solution can help you.
