### ISSUE TITLE
Question about the MNIST-DVS dataset

### ISSUE THREAD

**Issue by zhangxiann** [PIX2NVS/NVS2Graph#13]
In the paper, you said 
> For the N-MNIST, MNIST-DVS and NCARS datasets, we use the predefined training and testing splits, ...

But I found there is no predefined training and testing splits for MNIST-DVS dataset in the dataset website:(http://www2.imse-cnm.csic.es/caviar/MNIST_DVS/)[http://www2.imse-cnm.csic.es/caviar/MNIST_DVS/].
Could you please tell me how to construct training and testing splits ??

**Comment by zhangxiann** [comment]
![image](https://user-images.githubusercontent.com/12131262/120970442-05bd8a00-c79e-11eb-86f3-d29de5dff3ee.png)
No predefined training and testing splits !

**Comment by PIX2NVS** [comment]
Hi, thanks for the interests. For datasets that do not contain predefined training and testing splits, 20% of the data is randomly selected for testing and the remaining is used for training.
