### ISSUE TITLE
ASL-DVS Train/Test splits

### ISSUE THREAD

**Issue by AlbertoSabater** [PIX2NVS/NVS2Graph#14]
The article states that the test split of the proposed ASL-DVS dataset is built with 20% of the total data. Are those generated data splits public or could you provide more information on how they have been generated?

Thanks in advance.

**Comment by PIX2NVS** [comment]
Hi, thanks for the interests. There is no standard splits for training and testing. Just randomly select 20% of the data for testing and the remaining is used for training. You can do it several times and average results.
