### ISSUE TITLE
Method to achieve network inputs

### ISSUE THREAD

**Issue by YongjianDeng** [PIX2NVS/NVS2Graph#3]
Hi,

First of all, thank to you to provide such a fabulous method to solve event-based classification tasks. However, through your code, I did not find the code relates to transfer raw events to your input ( features, edge_index, pos et.al. Is there somewhere I missed or you have released this part of codes on other sites?

Best wishes,

**Comment by PIX2NVS** [comment]
Hi, thanks for your interests and sorry for the late reply because of holiday break.
We did not release the code for graph construction yet since lots of our future work is based on graph representation. We will open a new Repo for this part of code in the future.
