### ISSUE TITLE
The detail for doing non-uniform sampling in data-preprocessing part

### ISSUE THREAD

**Issue by oneliey** [PIX2NVS/NVS2Graph#5]
Can you provide the code of non-uniform sampling in data-preprocessing part？Thanks

**Comment by PIX2NVS** [comment]
Please refer to #4 for more details.

**Comment by oneliey** [comment]
What is the specific definition of  the space-time volume? Can I think a different coordinate as  a differeent grid? How long is the time in the space-time volume? Thanks

**Comment by PIX2NVS** [comment]
Replied you via email.
