### ISSUE TITLE
Test_Mo.py missing arguments

### ISSUE THREAD

**Issue by oneliey** [PIX2NVS/NVS2Graph#6]
![image](https://user-images.githubusercontent.com/30212642/79624664-d5f49280-8155-11ea-8d06-dce816831ae3.png)
No value for argument 'kernel_size' in the GMMConv constructor call

**Comment by PIX2NVS** [comment]
Thanks for your interests.
This is the version problem of pytorch_geometric.  In the previous version, there is the default value for kernel size (k=3). Just set K=3 when you run the Test_Mo.py.

**Comment by PIX2NVS** [comment]
Btw, the version of pytorch_geometric that I am using for these codes is 1.1.2.
Feel free to let me know if more conflicts of version.

**Comment by oneliey** [comment]
thx~
