### ISSUE TITLE
How to generate the *.mat file ?

### ISSUE THREAD

**Issue by zhangxiann** [PIX2NVS/NVS2Graph#7]
As I know, the original format of the data file is `*.txt`, in which each row represents a tuple (xi, yi, ti, pi). 
In the `inputsdata.py`, I find the data ends with `*.mat`, which contains four attributes: feature，edge，pseudo，label. 
But I can not find the code that generates these `*.mat` files.  I think this step of code corresponds to the `Nonuniform Sampling & Graph Construction` section of the paper. Is it right ?
And how can I find these code ?

**Comment by maricante** [comment]
There is info on this in the following issues:
https://github.com/PIX2NVS/NVS2Graph/issues/3
https://github.com/PIX2NVS/NVS2Graph/issues/4

**Comment by zhangxiann** [comment]
Thanks
